"""
generate_silo_router.py  (STAGE 3.65 — ad-group silo enforcement script)
-------------------------------------------------------------------------
Negatives written at build time are a prediction. Phrase match + close
variants still leak: "samsung fridge repair" can be served by the generic
Refrigerator Repair group instead of the Brands group, and then it gets the
generic ad, the generic bid and the wrong Quality Score history.

This writes `silo_router_script.js`: a Google Ads Script (run hourly) that
reads the last 14 days of search terms, classifies each one with the SAME
rules as Stage 2.7 (service -> layer precedence problem > brand > urgent >
core), and when a term was served by an ad group that does not own it, adds
an EXACT negative [term] to the wrong group only. The owning group keeps it.

Safety:
  - DRY_RUN = true by default: logs what it would do.
  - Never touches a term that converted in the group that served it.
  - Only acts when the owning group exists and is ENABLED in the same
    campaign (otherwise blocking would lose the query entirely).
  - Terms matching no service are left to the negative-guard script.

Input : ad_group_plan.json (+ keyword_strategy.json for the campaign name)
Output: silo_router_script.js
"""

import os
import sys
import json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import service_architecture as vtsa  # noqa: E402

PLAN = "ad_group_plan.json"
STRATEGY = "keyword_strategy.json"
OUT = "silo_router_script.js"

JS = r"""/**
 * SILO ROUTER — generated by the keyword pipeline (Stage 3.65)
 * Campaign: __CAMPAIGN__
 * Schedule: hourly. Keep DRY_RUN = true for the first 2-3 runs, read the log.
 */
var DRY_RUN = true;
var CAMPAIGN_NAME = __CAMPAIGN_JSON__;
var LOOKBACK = 'LAST_14_DAYS';
var MIN_IMPRESSIONS = 2;

var SERVICES = __SERVICES__;         // [{name, aliases:[...]}] longest alias first
var GROUPS = __GROUPS__;             // {"service|layer": "ad group name"}
var BRANDS = __BRANDS__;
var BRAND_PHRASES = __BRAND_PHRASES__;   // multi-word: "ال جي", "fisher paykel"
var PROBLEM_TRIGGERS = __PROBLEM__;
var URGENT_PHRASES = __URGENT__;
var ERROR_CODE = /^(?:[a-z]{1,2}\d{1,3}|\d{1,2}[a-z]{1,2})$/;

// Same Arabic normaliser as Stage 2.7: diacritics out, alef variants unified,
// the article stripped, feminine/plural ending stripped ("الثلاجات" -> "ثلاج").
function arNorm(w) {
  w = w.replace(/[\u064B-\u0652\u0640]/g, '').replace(/[أإآ]/g, 'ا').replace(/ى/g, 'ي');
  if (w.length <= 3) return w;
  var pres = ['وال', 'بال', 'فال', 'كال', 'لل', 'ال'];
  for (var i = 0; i < pres.length; i++) {
    if (w.indexOf(pres[i]) === 0 && w.length - pres[i].length >= 3) { w = w.slice(pres[i].length); break; }
  }
  var sufs = ['ات', 'ة', 'ه'];
  for (var j = 0; j < sufs.length; j++) {
    var s = sufs[j];
    if (w.slice(-s.length) === s && w.length - s.length >= 3) { w = w.slice(0, -s.length); break; }
  }
  return w;
}
function isArabic(t) { return /[\u0600-\u06FF]/.test(t); }
function norm(t) {
  var words = t.toLowerCase().replace(/[^\w\u0600-\u06FF\/]+/g, ' ').replace(/\s+/g, ' ').trim().split(' ');
  return ' ' + words.map(function (w) { return isArabic(w) ? arNorm(w) : w; }).join(' ') + ' ';
}
function has(text, phrase) { return text.indexOf(' ' + phrase + ' ') !== -1; }

function serviceOf(text) {
  var best = null, bestLen = 0, bestPos = 1e9;
  var lang = isArabic(text) ? 'ar' : 'en';
  for (var i = 0; i < SERVICES.length; i++) {
    if ((SERVICES[i].lang || 'en') !== lang) continue;
    for (var j = 0; j < SERVICES[i].aliases.length; j++) {
      var a = SERVICES[i].aliases[j];
      if (has(text, a)) {
        var len = a.split(' ').length, pos = text.indexOf(' ' + a + ' ');
        if (len > bestLen || (len === bestLen && pos < bestPos)) { best = SERVICES[i]; bestLen = len; bestPos = pos; }
      }
    }
  }
  return best;
}

function layerOf(text, svc) {
  var toks = text.trim().split(' ');
  var aliasToks = {};
  svc.aliases.forEach(function (a) { a.split(' ').forEach(function (w) { aliasToks[w] = 1; }); });
  for (var i = 0; i < toks.length; i++) {
    if (aliasToks[toks[i]]) continue;
    if (PROBLEM_TRIGGERS.indexOf(toks[i]) !== -1 || ERROR_CODE.test(toks[i])) return 'problem';
  }
  for (i = 0; i < toks.length; i++) if (BRANDS.indexOf(toks[i]) !== -1) return 'brand';
  for (i = 0; i < BRAND_PHRASES.length; i++) if (has(text, BRAND_PHRASES[i])) return 'brand';
  for (i = 0; i < URGENT_PHRASES.length; i++) if (has(text, URGENT_PHRASES[i])) return 'urgent';
  return 'core';
}

function ownerOf(term) {
  var text = norm(term);
  var svc = serviceOf(text);
  if (!svc) return null;
  var layer = layerOf(text, svc);
  return GROUPS[svc.name + '|' + layer] || GROUPS[svc.name + '|core'] || null;
}

function main() {
  var enabled = {};
  var agIt = AdsApp.adGroups()
    .withCondition("CampaignName = '" + CAMPAIGN_NAME.replace(/'/g, "\\'") + "'")
    .withCondition('Status = ENABLED').get();
  var byName = {};
  while (agIt.hasNext()) { var ag = agIt.next(); enabled[ag.getName().toLowerCase()] = 1; byName[ag.getName().toLowerCase()] = ag; }

  var q = "SELECT search_term_view.search_term, ad_group.name, metrics.impressions, metrics.conversions " +
          "FROM search_term_view WHERE campaign.name = '" + CAMPAIGN_NAME.replace(/'/g, "\\'") + "' " +
          "AND segments.date DURING " + LOOKBACK;
  var rows = AdsApp.search(q);
  var moved = 0, seen = {};
  while (rows.hasNext()) {
    var r = rows.next();
    var term = r.searchTermView.searchTerm, served = r.adGroup.name;
    var key = served + '||' + term;
    if (seen[key]) continue; seen[key] = 1;
    if (Number(r.metrics.impressions) < MIN_IMPRESSIONS) continue;
    if (Number(r.metrics.conversions) > 0) continue;            // never touch a converter
    var owner = ownerOf(term);
    if (!owner || owner.toLowerCase() === served.toLowerCase()) continue;
    if (!enabled[owner.toLowerCase()]) continue;                 // owner missing: keep the query
    moved++;
    Logger.log((DRY_RUN ? '[DRY] ' : '') + 'route "' + term + '": ' + served + ' -> ' + owner);
    if (!DRY_RUN && byName[served.toLowerCase()]) {
      byName[served.toLowerCase()].createNegativeKeyword('[' + term + ']');
    }
  }
  Logger.log('Silo router: ' + moved + ' mis-routed term(s)' + (DRY_RUN ? ' (dry run — nothing changed)' : ' negated in the wrong group'));
}
"""


def main():
    if not os.path.exists(PLAN):
        print(f"ℹ️ {PLAN} not found (legacy run) — silo router skipped.")
        return
    with open(PLAN, encoding="utf-8") as f:
        plan = json.load(f)
    if plan.get("fallback_legacy"):
        print("ℹ️ Plan fell back to legacy grouping — silo router skipped.")
        return
    camp = ""
    if os.path.exists(STRATEGY):
        with open(STRATEGY, encoding="utf-8") as f:
            camp = ((json.load(f).get("campaigns") or [{}])[0]).get("name", "")
    services = [{"name": s["name"], "aliases": s["aliases"], "lang": s.get("lang", "en")}
                for s in plan["services"]]
    groups = {f'{g["service"]}|{g["layer"]}': g["name"] for g in plan["ad_groups"]}
    problem = sorted({"لا"} | vtsa._NEGATIONS
                     | {t for t in vtsa.PROBLEM_TOKENS if t not in vtsa._GENERIC_PART_WORDS})
    urgent = sorted(set(vtsa._URGENT_PHRASES)
                    | {"emergency", "urgent", "nearby", "near", "local", "24", "same day"})
    js = (JS.replace("__CAMPAIGN__", camp or "(set CAMPAIGN_NAME)")
            .replace("__CAMPAIGN_JSON__", json.dumps(camp))
            .replace("__SERVICES__", json.dumps(services, ensure_ascii=False))
            .replace("__GROUPS__", json.dumps(groups, ensure_ascii=False, indent=1))
            .replace("__BRANDS__", json.dumps(sorted(b for b in vtsa.BRANDS if " " not in b and b not in vtsa._WEAK_BRANDS)))
            .replace("__BRAND_PHRASES__", json.dumps(sorted({vtsa.norm_phrase(b) for b in vtsa.BRANDS if " " in b}
                                                            | {" ".join(pr) for pr in vtsa._BRAND_PAIRS}),
                                                           ensure_ascii=False))
            .replace("__PROBLEM__", json.dumps(problem, ensure_ascii=False))
            .replace("__URGENT__", json.dumps(urgent, ensure_ascii=False)))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"✅ {OUT}: {len(groups)} ad groups routed across {len(services)} services (DRY_RUN on)")


if __name__ == "__main__":
    main()
